package com.tunisia.commerce.enums;

public enum DocumentType {
    // Documents entreprise
    RC_CERT, RC_TRANSLATION, RC_LEGALIZATION,
    STATUTES, STATUTES_TRANSLATION,
    TIN_CERT,

    // Documents représentant
    PASSPORT, DESIGNATION_PV,

    // Documents financiers
    SOLVENCY_CERT, ANNUAL_ACCOUNTS, EXTERNAL_AUDIT,

    // Documents produits alimentaires
    TECHNICAL_DATA_SHEET,
    SANITARY_APPROVAL,
    SANITARY_CERT,
    FREE_SALE_CERT,
    BACTERIO_ANALYSIS,
    PHYSICO_CHEM_ANALYSIS,
    RADIOACTIVITY_ANALYSIS,
    FUMIGATION_CERT,
    HACCP_ISO_CERT,
    BRAND_LICENSE,
    COMPETENT_AUTHORITY_LETTER,
    STORAGE_FACILITY_PLAN,
    PRODUCTION_FACILITY_PLAN,
    MONITORING_PLAN,
    PRODUCT_SPECIFICATION,
    PRODUCT_LABELS,
    COMMISSION_LETTER,
    QUALITY_CERT,
    PRODUCT_SHEETS,
    OFFICIAL_LETTER,

    // documents industriels
    CONFORMITY_CERT_ANALYSIS_REPORT,
}